from __future__ import annotations

import json
from typing import Any

import yaml

from android_test_agent.agent.capabilities import build_android_capabilities
from android_test_agent.agent.config import AndroidTestConfig
from android_test_agent.dsl.schema import normalize_test_name, validate_intent_dsl


class PytestAppiumCodeGenerator:
    """Generate stable pytest/Appium code from the agent DSL."""

    def __init__(self, config: AndroidTestConfig) -> None:
        self._config = config

    def write(self, dsl: dict[str, Any], output_name: str | None = None) -> dict[str, str]:
        validate_intent_dsl(dsl)
        test_name = output_name or normalize_test_name(dsl["name"])
        dsl_dir = self._config.generated_dir / "dsl"
        tests_dir = self._config.generated_dir / "tests"
        dsl_dir.mkdir(parents=True, exist_ok=True)
        tests_dir.mkdir(parents=True, exist_ok=True)

        dsl_path = dsl_dir / f"{test_name}.yaml"
        test_path = tests_dir / f"test_{test_name}.py"
        dsl_path.write_text(yaml.safe_dump(dsl, allow_unicode=True, sort_keys=False), encoding="utf-8")
        test_path.write_text(self.render_pytest(dsl, test_name), encoding="utf-8")
        return {"dsl": str(dsl_path), "pytest": str(test_path)}

    def render_pytest(self, dsl: dict[str, Any], test_name: str | None = None) -> str:
        test_name = test_name or normalize_test_name(dsl["name"])
        escaped_dsl = json.dumps(dsl, ensure_ascii=False, indent=2)
        capabilities = self._capabilities(dsl)
        escaped_capabilities = json.dumps(capabilities, ensure_ascii=False, indent=2)
        return f'''"""
Generated by android_test_agent.
Do not hand edit this file; update the source test case or generator instead.
"""

from __future__ import annotations

from datetime import datetime
import json
from pathlib import Path

import pytest
from appium import webdriver
from appium.options.android import UiAutomator2Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait

from android_test_agent.agent.config import AndroidTestConfig
from android_test_agent.dsl.action_runtime import AndroidDslActionRuntime
from android_test_agent.dsl.locator_resolver import LocatorResolutionError, LocatorResolver


def find_project_root():
    current = Path(__file__).resolve()
    for parent in current.parents:
        if (parent / "android_test_agent").exists():
            return parent
    return Path.cwd().resolve()


TEST_DSL = json.loads({escaped_dsl!r})
APPIUM_SERVER_URL = {self._config.appium_server_url!r}
CAPABILITIES = json.loads({escaped_capabilities!r})
EXPLICIT_WAIT_SECONDS = {self._config.explicit_wait_seconds}
IMPLICIT_WAIT_SECONDS = {self._config.implicit_wait_seconds}
REMEMBER_RUNTIME_LOCATORS = False
PROJECT_ROOT = find_project_root()
ARTIFACTS_DIR = PROJECT_ROOT / "artifacts"

if CAPABILITIES.get("appium:app"):
    app_path = Path(CAPABILITIES["appium:app"])
    if not app_path.is_absolute():
        app_path = PROJECT_ROOT / app_path
    CAPABILITIES["appium:app"] = str(app_path)

RESOLVER_CONFIG = AndroidTestConfig(
    project_root=PROJECT_ROOT,
    generated_dir=PROJECT_ROOT / "generated",
    artifacts_dir=ARTIFACTS_DIR,
    reports_dir=PROJECT_ROOT / "reports",
    checkpoint_dir=PROJECT_ROOT / "reports" / "checkpoints",
    checkpoint_db_path=PROJECT_ROOT / "reports" / "checkpoints" / "langgraph.sqlite",
    knowledge_dir=PROJECT_ROOT / "knowledge",
    appium_server_url=APPIUM_SERVER_URL,
    platform_name=CAPABILITIES.get("platformName", "Android"),
    device_name=CAPABILITIES.get("appium:deviceName", "Android Emulator"),
    app_package=CAPABILITIES.get("appium:appPackage"),
    app_activity=CAPABILITIES.get("appium:appActivity"),
    apk_path=CAPABILITIES.get("appium:app"),
    implicit_wait_seconds=IMPLICIT_WAIT_SECONDS,
    explicit_wait_seconds=EXPLICIT_WAIT_SECONDS,
)
LOCATOR_RESOLVER = LocatorResolver(RESOLVER_CONFIG)
ACTION_RUNTIME = AndroidDslActionRuntime(
    RESOLVER_CONFIG,
    locator_resolver=LOCATOR_RESOLVER,
    artifacts_dir=ARTIFACTS_DIR,
    failure_prefix={test_name!r},
    remember_runtime_locators=REMEMBER_RUNTIME_LOCATORS,
)


@pytest.fixture()
def driver():
    options = UiAutomator2Options().load_capabilities(CAPABILITIES)
    driver = webdriver.Remote(APPIUM_SERVER_URL, options=options)
    driver.implicitly_wait(IMPLICIT_WAIT_SECONDS)
    try:
        yield driver
    finally:
        driver.quit()


def resolve_locator(driver, target, action):
    try:
        return LOCATOR_RESOLVER.resolve_target(
            target,
            page_source=driver.page_source,
            action=action,
        )
    except LocatorResolutionError as exc:
        write_locator_failure_artifacts(driver, action, target, exc)
        raise


def appium_locator(locator):
    by = locator["by"]
    value = locator["value"]
    mapping = {{
        "id": By.ID,
        "android_uiautomator": "-android uiautomator",
        "accessibility_id": "accessibility id",
        "xpath": By.XPATH,
        "text": By.XPATH,
    }}
    if by not in mapping:
        raise ValueError(f"Unsupported locator strategy: {{by}}")
    if by == "text":
        value = f"//*[@text={{xpath_literal(value)}}]"
    return mapping[by], value


def candidate_targets(resolved_target):
    candidates = []
    seen = set()

    def add_candidate(locator, candidate=None):
        if not isinstance(locator, dict) or not locator.get("by") or not locator.get("value"):
            return
        key = (str(locator["by"]), str(locator["value"]))
        if key in seen:
            return
        seen.add(key)
        candidate_target = dict(resolved_target)
        candidate_target["locator"] = {{"by": key[0], "value": key[1]}}
        if candidate:
            candidate_target["locator_source"] = candidate.get("source", candidate_target.get("locator_source"))
            candidate_target["locator_score"] = candidate.get("score", candidate_target.get("locator_score"))
            candidate_target["locator_reason"] = candidate.get("reason", candidate_target.get("locator_reason"))
            if candidate.get("metadata"):
                candidate_target["locator_metadata"] = candidate["metadata"]
        candidates.append(candidate_target)

    add_candidate(resolved_target.get("locator"))
    for candidate in resolved_target.get("locator_candidates", []):
        if isinstance(candidate, dict):
            add_candidate(candidate.get("locator"), candidate)
    return candidates


def find_matching_element(driver, by, value, target, action):
    elements = driver.find_elements(by, value)
    visible_elements = [element for element in elements if safe_is_displayed(element)]
    if not visible_elements:
        return False
    if len(visible_elements) == 1:
        return visible_elements[0]
    return best_runtime_element(visible_elements, target, action) or visible_elements[0]


def best_runtime_element(elements, target, action):
    metadata = target.get("locator_metadata") if isinstance(target, dict) else None
    if not isinstance(metadata, dict) or not metadata:
        return None
    scored = [(runtime_element_score(element, metadata, action), element) for element in elements]
    scored.sort(key=lambda item: item[0], reverse=True)
    return scored[0][1] if scored and scored[0][0] > 0 else None


def runtime_element_score(element, metadata, action):
    score = 0.0
    expected_text = normalized(metadata.get("text"))
    expected_desc = normalized(metadata.get("content_desc"))
    expected_class = normalized(metadata.get("class"))
    expected_bounds = str(metadata.get("bounds") or "")

    actual_text = normalized(element_attribute(element, "text", "name"))
    actual_desc = normalized(element_attribute(element, "content-desc", "contentDescription", "name"))
    actual_class = normalized(element_attribute(element, "class", "className"))
    actual_bounds = str(element_attribute(element, "bounds") or "")

    if expected_text and actual_text == expected_text:
        score += 0.45
    elif expected_text and expected_text in actual_text:
        score += 0.25
    if expected_desc and actual_desc == expected_desc:
        score += 0.35
    if expected_class and actual_class == expected_class:
        score += 0.15
    if expected_bounds and actual_bounds == expected_bounds:
        score += 0.25
    if action == "tap" and truthy(element_attribute(element, "clickable")):
        score += 0.15
    if metadata.get("enabled") is True and truthy(element_attribute(element, "enabled")):
        score += 0.05
    return score


def element_attribute(element, *names):
    for name in names:
        try:
            value = element.get_attribute(name)
        except Exception:
            value = None
        if value not in (None, ""):
            return str(value)
    return str(getattr(element, "text", "") or "")


def safe_is_displayed(element):
    try:
        return bool(element.is_displayed())
    except Exception:
        return False


def truthy(value):
    return str(value).lower() in {{"true", "1", "yes"}}


def normalized(value):
    return str(value or "").strip().lower()


def xpath_literal(value):
    value = str(value)
    if "'" not in value:
        return "'" + value + "'"
    if '"' not in value:
        return '"' + value + '"'
    separator = ', ' + '"' + "'" + '"' + ', '
    return "concat(" + separator.join("'" + part + "'" for part in value.split("'")) + ")"


def uiselector_literal(value):
    value = str(value).replace("\\\\", "\\\\\\\\").replace('"', '\\\\"')
    return f'"{{value}}"'


def wait_for(driver, target, action):
    resolved_target = resolve_locator(driver, target, action)
    attempts = []
    last_error = None
    for candidate_target in candidate_targets(resolved_target):
        by, value = appium_locator(candidate_target["locator"])
        try:
            driver.implicitly_wait(0)
            try:
                element = WebDriverWait(driver, EXPLICIT_WAIT_SECONDS).until(
                    lambda current_driver: find_matching_element(current_driver, by, value, candidate_target, action)
                )
            finally:
                driver.implicitly_wait(IMPLICIT_WAIT_SECONDS)
        except Exception as exc:
            last_error = exc
            attempts.append(
                {{
                    "locator": candidate_target.get("locator"),
                    "source": candidate_target.get("locator_source"),
                    "score": candidate_target.get("locator_score"),
                    "error": str(exc),
                }}
            )
            continue

        if REMEMBER_RUNTIME_LOCATORS:
            LOCATOR_RESOLVER.remember(candidate_target, action=action, page_source=driver.page_source)
        return element

    error = last_error or LocatorResolutionError("No locator candidates were available")
    failure_target = {{"target": target, "resolved_target": resolved_target, "attempts": attempts}}
    write_locator_failure_artifacts(driver, action, failure_target, error)
    raise error


def wait_for_text(driver, text):
    try:
        driver.implicitly_wait(0)
        try:
            return WebDriverWait(driver, EXPLICIT_WAIT_SECONDS).until(
                lambda current_driver: find_visible_text(current_driver, text)
            )
        finally:
            driver.implicitly_wait(IMPLICIT_WAIT_SECONDS)
    except Exception as exc:
        write_locator_failure_artifacts(driver, "assert_text", {{"text": text}}, exc)
        raise


def find_visible_text(driver, text):
    literal = xpath_literal(text)
    elements = driver.find_elements(By.XPATH, f"//*[@text={{literal}} or @content-desc={{literal}}]")
    visible_elements = [element for element in elements if safe_is_displayed(element)]
    return visible_elements[0] if visible_elements else False


def scroll_to_text(driver, text):
    selector = (
        "new UiScrollable(new UiSelector().scrollable(true))"
        f".scrollIntoView(new UiSelector().text({{uiselector_literal(text)}}))"
    )
    try:
        driver.implicitly_wait(0)
        try:
            driver.find_element("-android uiautomator", selector)
            return wait_for_text(driver, text)
        finally:
            driver.implicitly_wait(IMPLICIT_WAIT_SECONDS)
    except Exception as exc:
        write_locator_failure_artifacts(driver, "scroll_to_text", {{"text": text}}, exc)
        raise


def write_locator_failure_artifacts(driver, action, target, error):
    output_dir = ARTIFACTS_DIR / "locator_failures"
    output_dir.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S_%f")
    prefix = output_dir / f"{test_name}_{{timestamp}}"
    page_source = getattr(driver, "page_source", "")
    if page_source:
        prefix.with_suffix(".xml").write_text(page_source, encoding="utf-8")
    prefix.with_suffix(".json").write_text(
        json.dumps(
            {{"action": action, "target": target, "error": str(error)}},
            ensure_ascii=False,
            indent=2,
        ),
        encoding="utf-8",
    )
    try:
        driver.save_screenshot(str(prefix.with_suffix(".png")))
    except Exception:
        pass


def launch_app(driver):
    app_package = CAPABILITIES.get("appium:appPackage")
    app_activity = CAPABILITIES.get("appium:appActivity")
    if not app_package:
        return
    if app_activity:
        component = app_activity if "/" in app_activity else f"{{app_package}}/{{app_activity}}"
        try:
            driver.execute_script("mobile: startActivity", {{"component": component, "stopApp": True}})
            return
        except Exception:
            pass
    driver.activate_app(app_package)


def run_step(driver, step):
    ACTION_RUNTIME.run_step(driver, step)


def test_{test_name}(driver):
    for step in TEST_DSL["steps"]:
        run_step(driver, step)
'''

    def _capabilities(self, dsl: dict[str, Any]) -> dict[str, Any]:
        return build_android_capabilities(self._config, dsl)
